spring:
  application:
    name: customer-backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/customer-db
    username: user
    password: secret
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
  jpa:
    show-sql: false
    properties:
      hibernate: org.hibernate.dialect.PostgresSQLDialect
      format_sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html